apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: dev
spec:
  type: NodePort        # expose the service outside the cluster
  selector:
    app: my-app
  ports:
    - port: 8888       # cluster port
      targetPort: 8888 # container port
      nodePort: 8888   # host port you want to use (your VM port)
