apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 8888         # container sees this as 8888
      targetPort: 8888
      nodePort: 31833    # exposed on host
      protocol: TCP
